# Generated by Django 3.2.6 on 2021-08-28 14:35

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_text', models.CharField(max_length=500)),
                ('post_date', models.DateTimeField(verbose_name='date posted')),
                ('business_type', models.CharField(choices=[('F', 'Farm'), ('R', 'Restaurant')], max_length=1)),
                ('request_photo', models.ImageField(upload_to=backend.models.request_directory_path)),
            ],
        ),
    ]
