# Generated by Django 3.2.6 on 2021-08-28 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20210828_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fulfillment_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='contacts',
            name='business_type',
            field=models.CharField(choices=[('R', 'Restaurant'), ('F', 'Farm')], default='R', max_length=1),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.AddField(
            model_name='orders',
            name='contact_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.contacts'),
        ),
    ]
